/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://twtdjz6sabgiln4idoop66lc6q.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:d86a48a3-e25f-4934-851f-2c154ca7a115",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FAQf5oYGp",
    "aws_user_pools_web_client_id": "4aq45ckp2ot054ichndrp668b2",
    "oauth": {},
    "aws_user_files_s3_bucket": "vincolibrarys3100304-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
