/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:efaf6e4d-899c-4805-a0cd-2dda6c7b0c21",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_iPxuObiqo",
    "aws_user_pools_web_client_id": "2c035r4dd94l57fcoj1q831kb1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://okihjj3zefgw3irco2ydecc3gq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "vincoelearningbucket81733-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
